
general {
    # ロック呼び出し
    lock_cmd = pidof hyprlock || hyprlock

    # スリープ前にロック
    before_sleep_cmd = loginctl lock-session

    # 復帰時に画面ON
    after_sleep_cmd = hyprctl dispatch dpms on
}

# ① 少し暗く
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 20
    on-resume = brightnessctl -r
}

# ② ロック
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# ③ 画面OFF
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# ④ スリープ
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
