--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
  name = "suppress-all",
  match = {
    class = ".*",
  },
  suppress_event = "fullscreen maximize activate activatefocus",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
  name = "no-initfocus-xwayland",
  match = {
    class = "^$",
    title = "^$",
    xwayland = 1,
    float = 1,
    fullscreen = 0,
  },
  no_initial_focus = true,
  pin = false,
})
