-- lua/plugins/init.lua
return {

  require("plugins.conform"),
  require("plugins.noice"),
  require("plugins.dashboard"),
  require("plugins.playground"),
  require("plugins.ts_text_obj"),
  require("plugins.treesitter"),
  require("plugins.hlchunk"),
  require("plugins.barbar"),
  require("plugins.lua_line"),
  require("plugins.nvim_tree"),
  require("plugins.toggle_term"),
  require("plugins.lazy_git"),
  require("plugins.git_sign"),
  require("plugins.diff_view"),
  require("plugins.ts_context"),
  require("plugins.dropbar"),
  require("plugins.scrollbar"),
  require("plugins.accelerated"),
  require("plugins.ufo"),
  require("plugins.comment_box"),
  require("plugins.dial"),
  require("plugins.glance"),
  require("plugins.namu"),
  require("plugins.doge"),
  require("plugins.markview"),
  require("plugins.winresizer"),
  require("plugins.surround"),
  require("plugins.autopairs"),
  require("plugins.operator_conv_case"),
  require("plugins.operator_user"),
  require("plugins.operator_replace"),
  require("plugins.auto_save"),
  require("plugins.repeat"),
  require("plugins.plenary"),
  require("plugins.telescope"),
  require("plugins.lsp_signature"),
  require("plugins.trouble"),
  require("plugins.translator"),
  require("plugins.mason"),
  require("plugins.mason_lspconf"),
  require("plugins.none_ls"),
  require("plugins.mason_null_ls"),
  require("plugins.lspconfig"),
  require("plugins.cmp"),

  -- 「プラグインを追加したらここに続けて記述」
}