#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24

env = GTK_THEME,Adwaita:dark
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

env = ELECTRON_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

env = XDG_PICTURES_DIR,$HOME/Pictures
env = HYPRSHOT_DIR,$HOME/Pictures



#########################
### LINK CONFIG FILES ###
#########################

source = ~/.config/hypr/common/look_and_feel.conf 
source = ~/.config/hypr/common/window_rule.conf 
source = ~/.config/hypr/common/window_and_workspaces.conf
source = ~/.config/hypr/common/key_bindings.conf 
source = ~/.config/hypr/common/autostart.conf
source = ~/.config/hypr/common/monitors_and_inputs_NCP-2602.conf

